name: Update Cases

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0,30 * * * *

jobs:
  update_cases:
    runs-on: ubuntu-latest
    steps:    

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'

      - name: Run tracking script
        run: go run scripts/track.go

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=changes_exist::false"
          else
            echo "::set-env name=changes_exist::true"
          fi

      - name: Commit and push only if changes
        if: env.changes_exist == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --verbose .
          git commit -m "generated"
          git push origin main

    
